### ISSUE TITLE
Cannot parse bttv emote "(ditto)"

### ISSUE THREAD

**Issue by ShowTsai** [smilefx/tmi-emote-parse#2]
As the title.

[(ditto)](https://cdn.betterttv.net/emote/554da1a289d53f2d12781907/3x)

**Comment by smilefx** [comment]
Is done and will be pushed with the next update!

**Comment by smilefx** [comment]
Resolved in [v1.2.0+](https://github.com/smilefx/tmi-emote-parse/commit/aad1548294add175b55b8a69044ae0095dc90a8b).
