### ISSUE TITLE
The user info api endpoint has incorrrect CORS configuration

### ISSUE THREAD

**Issue by jakubbilko** [smilefx/tmi-emote-parse#7]
The `https://dadoschyt.de/api/tmt/user/[channel]` endpoint has CORS configured incorrectly, casing issues.

**Comment by smilefx** [comment]
This issue should now be resolved following the deprecation of the mentioned endpoint in [v2.0.0](https://github.com/smilefx/tmi-emote-parse/releases/tag/v2.0.0).
